import type { Metadata } from 'next';
import { Montserrat, Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans-kr',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

const jalnan = localFont({
  src: './fonts/Jalnan.ttf',
  display: 'swap',
  variable: '--font-jalnan',
});

const lotteMart = localFont({
  src: './fonts/LotteMart.woff2',
  display: 'swap',
  variable: '--font-lotte-mart',
});

const haenam = localFont({
  src: './fonts/haenam.ttf',
  display: 'swap',
  variable: '--font-haenam',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${notoSansKR.variable} ${montserrat.variable} ${jalnan.variable} ${lotteMart.variable} ${haenam.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
